version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: all
  disable:
    - containedctx
    - depguard
    - dogsled
    - dupl
    - err113
    - errname
    - errorlint
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - importas
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - mnd
    - musttag
    - nakedret
    - nestif
    - nonamedreturns
    - nosprintfhostport
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testableexamples
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 30
      package-average: 0
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      excludes:
        - G110
        - G115
        - G305
      config:
        G306: "0755"
    interfacebloat:
      max: 12
    nlreturn:
      block-size: 2
    revive:
      severity: warning
    staticcheck:
      checks:
        - all
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: false
    goimports:
      local-prefixes:
        - github.com/hashicorp
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
