# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  format: colored-line-number
  # print lines of code with issue, default is true
  print-issued-lines: true
  # print linter name in the end of issue text, default is true
  print-linter-name: true
  # make issues output unique by line, default is true
  uniq-by-line: true
  # add a prefix to the output file references; default is no prefix
  # path-prefix: ""
  # sorts results by: filepath, line and column
  sort-results: false

# all available settings of specific linters
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  cyclop:
    max-complexity: 30
    package-average: 0.0
    skip-tests: false

  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/hashicorp

  gofumpt:
    extra-rules: false

  gosec:
    excludes:
      # Don't worry about decompression bombs, not relevant for our usage of zip
      - G110
      # Don't worry about zip file traversals
      - G305
    config:
      G306:
        # allow creating files with 0755 permissions
        "0755"

  interfacebloat:
    max: 12

  nlreturn:
    # Size of the block (including return statement that is still "OK")
    block-size: 2

  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: true
    severity: warning

linters:
  enable-all: true
  disable:
    - containedctx
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errname
    - errorlint
    - execinquery
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    # disabled for now
    - gocritic
    - gocyclo
    # disabled for now
    - godox
    - goerr113
    - gofmt
    - goheader
    - golint
    - gomnd
    - gomoddirectives # until we remove our go-cty fork
    - ifshort
    - importas
    - interfacer
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - maligned
    - musttag
    - nakedret
    - nestif
    - nonamedreturns
    - nosprintfhostport
    - nosnakecase
    - promlinter
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - tagliatelle
    - testableexamples
    - testpackage
    # disabled because it's not friendly with the terraform test helper
    - tparallel
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
  fast: false

severity:
  case-sensitive: false
